---
- name: Prepare
  hosts: all
  any_errors_fatal: true
  vars:
    paperless_ngx_version: latest
  tasks:
    - name: "Install latest version of pngx (reconfigure)"
      ansible.builtin.include_role:
        name: "stevenengland.paperless_ngx"
