---
- name: Check variables for logical errors
  ansible.builtin.include_tasks:
    file: vars.yml
    apply:
      tags: vars
  tags: vars

- name: Gather infos about the operating system
  ansible.builtin.include_tasks:
    file: os.yml
    apply:
      tags: os
  tags: os

- name: Gather infos about paperless-ngx versions
  ansible.builtin.include_tasks:
    file: version.yml
    apply:
      tags: version
  tags: version
