---
- name: Verify operating system
  ansible.builtin.assert:
    that: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
    msg: Sorry, only Debian and Ubuntu supported at the moment.

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Verify Ansible meets version requirements.
  ansible.builtin.assert:
    that: "ansible_version.full is version_compare('2.7', '>=')"
    msg: >
      "You must update Ansible to at least 2.7 to use this role."
