---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: ["-c=.yamllint.yml", "."]
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.11.0
    hooks:
      - id: ansible-lint
        args: ["-c", ".ansible-lint.yml"]
        files: \.(yaml|yml)$
