---
- name: Check if jbig2enc is already installed with correct version
  ansible.builtin.command:
    cmd: jbig2 --version
  register: _jbig2enc_version_installed_response
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Setting host facts using complex arguments  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    _jbig2enc_wanted_version_installed: >-
      {%- if _jbig2enc_version_installed_response.rc != 0 or _jbig2enc_version_installed_response.stdout.split(' ')[-1] != paperless_ngx_jbig2enc_version -%}
      false
      {%- else -%}
      true
      {%- endif -%}
