---
- name: Backup current paperless-ngx installation
  ansible.builtin.copy:
    src: "{{ paperless_ngx_directory }}"
    remote_src: true
    dest: "{{ paperless_ngx_directory }}-backup-{{ ansible_date_time.iso8601 }}/"
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
