---
- name: Backup current paperless-ngx installation
  become: true
  ansible.builtin.copy:
    src: "{{ paperless_ngx_dir_installation }}"
    remote_src: true
    dest: "{{ paperless_ngx_dir_installation }}-backup-{{ ansible_date_time.iso8601 }}/"
    owner: "{{ paperless_ngx_system_user }}"
    group: "{{ paperless_ngx_system_group }}"
    mode: 0600
