---
- name: Install latest pip
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ paperless_ngx_dir_virtualenv }}"
    virtualenv_python: python3
    extra_args: --upgrade

- name: Install paperless-ngx python requirements
  become: true
  become_user: "{{ paperless_ngx_system_user }}"
  ansible.builtin.pip:
    requirements: "{{ paperless_ngx_dir_installation }}/requirements.txt"
    virtualenv: "{{ paperless_ngx_dir_virtualenv }}"
    virtualenv_python: python3
    extra_args: --upgrade

#  Needs configuration first so that dirs etc. are known to pngx
# - name: Migrate database schema
#   become: true
#   become_user: "{{ paperless_ngx_system_user }}"
#   ansible.builtin.command: "{{ paperless_ngx_dir_virtualenv }}/bin/python3 {{ paperless_ngx_dir_installation }}/src/manage.py migrate"
#   register: _database_schema_migration
#   changed_when: '"No migrations to apply." not in _database_schema_migration.stdout'
#
# - name: "[NC] - Generate password {{ paperless_ngx_superuser_name }}"
#   become: true
#   ansible.builtin.set_fact:
#     paperless_ngx_superuser_password: "{{ lookup('password', '/root/pnx_superuser.pwd') }}"
#   when: paperless_ngx_superuser_password is not defined
#
# - name: Configure paperless superuser
#   become: true
#   become_user: "{{ paperless_ngx_system_user }}"
#   ansible.builtin.command: "{{ paperless_ngx_dir_virtualenv }}/bin/python3 {{ paperless_ngx_dir_installation }}/src/manage.py manage_superuser"
#   environment:
#     PAPERLESS_ADMIN_USER: "{{ paperless_ngx_superuser_name }}"
#     PAPERLESS_ADMIN_MAIL: "{{ paperless_ngx_superuser_email }}"
#     PAPERLESS_ADMIN_PASSWORD: "{{ paperless_ngx_superuser_password }}"
#   register: _superuser_created
#   changed_when: '"Created superuser" in _superuser_created.stdout'
#   no_log: true
#
# - name: set ownership and permissions on paperlessng venv
#   ansible.builtin.file:
#     path: "{{ paperlessng_virtualenv }}"
#     state: directory
#     recurse: true
#     owner: "{{ paperlessng_system_user }}"
#     group: "{{ paperlessng_system_group }}"
#     mode: g-w,o-rwx
#   when: venv.changed or not reconfigure_only
