---
- name: Create paperless system group
  become: true
  ansible.builtin.group:
    name: "{{ paperless_ngx_system_group }}"
    gid: "{{ omit if paperless_ngx_conf_usermap_gid in (None, omit) else paperless_ngx_conf_usermap_gid }}"

- name: Create paperless system user
  become: true
  ansible.builtin.user:
    name: "{{ paperless_ngx_system_user }}"
    uid: "{{ omit if paperless_ngx_conf_usermap_uid in (None, omit) else paperless_ngx_conf_usermap_uid }}"
    group: "{{ paperless_ngx_system_group }}"
    groups: "{{ paperless_ngx_system_user_additional_groups }}"
    append: true
    shell: /usr/sbin/nologin
    # GNUPG_HOME required due to paperless db.py
    create_home: true
