---
- name: Restart paperless completely
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ item }}"
    state: restarted
  with_items:
    - paperless-consumer.service
    - paperless-scheduler.service
    - paperless-webserver.service
    - paperless-task-queue.service

- name: Restart webserver
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ item }}"
    state: restarted
  with_items:
    - paperless-webserver.service
