---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include stevenengland.paperless_ngx_ansible_role"
      ansible.builtin.include_role:
        name: "stevenengland.paperless_ngx_ansible_role"
      tags:
        - preparation
        - base_dependencies
