---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include stevenengland.paperless_ngx"
      ansible.builtin.include_role:
        name: "stevenengland.paperless_ngx"
      tags:
        - preparation
        - base_dependencies
        - paperless_ngx
