---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${TEST_MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  if [ -z "${TEST_MOLECULE_LINT}" ] || [ "${TEST_MOLECULE_LINT}" = true  ]
  then
    echo "Molecule linting requested: true"
    yamllint -c=.yamllint.yml .
    ansible-lint -c .ansible-lint.yml
  else
    echo "Molecule linting requested: false"
  fi
