---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  if [ -z "${TEST_RUN_MOLECULE_LINT}" ] || [ "${TEST_RUN_MOLECULE_LINT}" = true  ]
  then
    echo "Molecule linting requested: true"
    yamllint -c=.yamllint.yml .
    ansible-lint -c .ansible-lint.yml
  else
    echo "Molecule linting requested: false"
  fi
