---
## Source: https://github.com/marketplace/actions/ansible-lint
name: Ansible Lint

"on":
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6
