---
name: Labeler

"on":
  push:
    branches:
      - master
  paths:
    - '.github/labels.yml'
    - '.github/workflows/label_creation.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: false
          skip-delete: false
