---
name: Tests

"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 5"  # At 07:00 on Friday

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  molecule_test:
    name: Molecule Test
    runs-on: ubuntu-latest
    needs:
      - linting

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt ansible molecule[docker] docker

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          TEST_MOLECULE_LINT: false
